{
  "error_during_communication": "خطأ أثناء التواصل: ",
  "handshake_exception": "خطأ في تحليل البيانات، لا يمكننا معالجة البيانات من الخادم. يرجى المحاولة مرة أخرى لاحقًا.",
  "unprocessable_response": "استجابة غير متوقعة من الخادم، نواجه مشكلات فنية مع خادمنا. يرجى المحاولة مرة أخرى لاحقًا.",
  "timed_out_or_no_internet": "انتهت مدة الاتصال أو لا يوجد اتصال بالإنترنت، يبدو أن هناك مشكلة في اتصالك بالإنترنت أو أن الخادم غير متاح. يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى.",
  "bad_request_exception": "عذرًا للإزعاج، واجهنا خطأ في الطلب. يرجى إعادة المحاولة مرة أخرى.",
  "unauthorized_exception": "تم رفض الوصول، ليس لديك الأذونات الكافية للوصول إلى هذا المورد. يرجى التأكد من المصادقة والتفويض للوصول إلى هذا المحتوى.",
  "forbidden_exception": "تم حظر الوصول، ليس لديك الإذن للوصول إلى المورد. يرجى التحقق من صلاحياتك لعرض أو تعديل هذا المحتوى.",
  "request_not_found_exception": "المورد غير موجود، لم يتم العثور على المورد المطلوب. يرجى التحقق من عنوان URL والمحاولة مرة أخرى.",
  "method_not_allowed_exception": "الطريقة غير مسموح بها، الطريقة المطلوبة غير مدعومة لهذا المورد.",
  "conflict_in_request_exception": "تعذر معالجة الطلب بسبب صراع في الطلب، يرجى المحاولة مرة أخرى.",
  "server_error_exception": "خطأ داخلي في الخادم، نأسف للإزعاج، ولكن حدث خطأ ما على جانبنا. يرجى المحاولة بعد بضع دقائق.",
  "service_unavailable_exceeption": "الخادم غير قادر حاليًا على معالجة الطلب بسبب التحميل الزائد المؤقت أو صيانة الخادم.",
  "unknown_error_exception": "خطأ غير معروف، حدث شيء غير متوقع. يرجى المحاولة مرة أخرى لاحقًا أو الاتصال بالدعم للمساعدة.",
  "vpn_usage_exception": "أنت تستخدم شبكة خاصة افتراضية (VPN)"
}